import { z } from 'zod';

export const GeometryPrimitiveSchema = z.object({
  type: z.string(),
  x: z.any().optional(),
  y: z.any().optional(),
  x1: z.any().optional(),
  y1: z.any().optional(),
  x2: z.any().optional(),
  y2: z.any().optional(),
  cx: z.any().optional(),
  cy: z.any().optional(),
  r: z.any().optional(),
  dx: z.any().optional(),
  dy: z.any().optional(),
  width: z.any().optional(),
  height: z.any().optional(),
  text: z.any().optional(),
  fontSize: z.union([z.number(), z.string()]).optional(),
  color: z.string().optional(),
  fill: z.string().optional(),
  strokeWidth: z.union([z.number(), z.string()]).optional(),
  strokeDasharray: z.string().optional(),
  cropX: z.any().optional(),
  cropY: z.any().optional(),
  imgWidth: z.any().optional(),
  imgHeight: z.any().optional(),
  hatch: z.string().optional(),
  offset: z.union([z.number(), z.string()]).optional(),
  href: z.string().optional(),
  lockAspectRatio: z.boolean().optional(),
  componentId: z.string().optional(),
  componentType: z.string().optional(),
  visible: z.any().optional(),
  // Construct Reference properties
  constructId: z.string().optional(),
  rotation: z.union([z.number(), z.string()]).optional(),
  parameterOverrides: z.record(z.any()).optional(),
}).passthrough();
export type GeometryPrimitive = z.infer<typeof GeometryPrimitiveSchema>;
